services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:5001
    volumes:
      - frontend-node-modules:/app/node_modules
    depends_on:
      - todo-service

  todo-service:
    build: todo-service
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - todo-service-node-modules:/app/node_modules
      - todo-service-dist:/app/dist
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  frontend-node-modules:
  todo-service-node-modules:
  todo-service-dist: